/*
* Ontological Header: getFibonacciSpherePoints.js
* Version: 1.0.0
* Date: August 10, 2025
* Author: Gemini
* Description: This module serves as the foundational spatial logic for the "HyperAetherPilgrim"
* visualizer. It generates a uniform, non-overlapping distribution of points on a sphere,
* which are used to position child nodes relative to a parent node. This prevents
* visual clutter and ensures clear parent-child relationships, crucial for
* effective data organization and navigation.
*
* Ontology Concepts Defined:
* Self (⚹): The module itself, as the foundational element of the visualizer's spatial logic.
* Thought: The golden angle algorithm, which is a mathematical thought that ensures uniform distribution.
* Logic: The specific mathematical calculations that precisely determine the coordinates of each point.
* Unity: The function's output (an array of THREE.Vector3 objects) that unifies abstract data with a tangible 3D space.
* Existence: The generated array of points, which gives a new set of objects a place to exist in the visualizer's universe.
* Improvement: The golden angle's ability to create a more efficient and elegant distribution of points than other methods.
* Mastery: The function's ability to perfectly solve the geometric problem of distributing points on a sphere.
* Resonance: The function enables the visualizer to create a fractal that resonates with the underlying data's relationships.
* Transcendence: The function provides a framework that allows a simple numerical input to transcend into a complex, organized 3D structure.
*
* Revisions:
* 1.0.0 (2025-08-10): Initial creation of the script.
*/*
* Role within System:
* - **Ontological Prime Module:** This function embodies the core principle of
* translating abstract relational data into a structured physical space.
* - **"Inward Development":** Serves as a key component of the internal planning tool,
* providing the framework for visualizing project tasks and concepts.
* - **"getPaid(zak)" Function:** Directly supports the outward-facing development
* by creating a clean, intuitive UI for data exploration and presentation.
*
* Dependencies:
* - **three.js:** Relies on the `THREE.Vector3` class for 3D vector representation.
*
* Relationships:
* - **Parent:** Main application logic that instantiates new nodes.
* - **Children:** The nodes themselves, positioned using the coordinates
* generated by this module.
*
*
* Author: [Your Name]
* Date: [Current Date]
*/
import * as THREE from 'three';

 // This function generates points on a sphere, ensuring branches don't overlap
       export function getFibonacciSpherePoints(samples, radius) {
            let points = [];
            const phi = Math.PI * (3. - Math.sqrt(5.)); // golden angle in radians
            for (let i = 0; i < samples; i++) {
                const y = 1 - (i / (samples - 1)) * 2; // y goes from 1 to -1
                const r = Math.sqrt(1 - y * y); // radius at y
                const theta = phi * i; // golden angle increment
                const x = Math.cos(theta) * r;
                const z = Math.sin(theta) * r;
                points.push(new THREE.Vector3(x, y, z).multiplyScalar(radius));
            }
            return points;
        